### ISSUE TITLE
I keep getting can't create conversation error

### ISSUE THREAD

**Issue by GaNjA-spec** [Soulter/hugging-chat-api#107]
C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\Scripts\python.exe C:/Users/D4RK_D4NTE/PycharmProjects/pythonProject2/main.py
Traceback (most recent call last):
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 124, in new_conversation
    cid = json.loads(resp.text)['conversationId']
KeyError: 'conversationId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\main.py", line 18, in <module>
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 49, in __init__
    self.current_conversation = self.new_conversation()
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 132, in new_conversation
    raise CreateConversationError(f"Failed to create new conversation. ({err_count})")
hugchat.exceptions.CreateConversationError: Failed to create new conversation. (6)

Process finished with exit code 1

**Comment by Whitelisted1** [comment]
Hello, @GaNjA-spec
Make sure that you have the latest version of `hugchat` installed with the command `pip install --upgrade hugchat`

**Comment by GaNjA-spec** [comment]
i already have the latest version installed

**Comment by GaNjA-spec** [comment]
Traceback (most recent call last):
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 124, in new_conversation
    cid = json.loads(resp.text)['conversationId']
KeyError: 'conversationId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\main.py", line 18, in <module>
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 49, in __init__
    self.current_conversation = self.new_conversation()
  File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 132, in new_conversation
    raise CreateConversationError(f"Failed to create new conversation. ({err_count})")
hugchat.exceptions.CreateConversationError: Failed to create new conversation. (6)

Process finished with exit code 1

**Comment by Whitelisted1** [comment]
> Traceback (most recent call last): File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 124, in new_conversation cid = json.loads(resp.text)['conversationId'] KeyError: 'conversationId'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\main.py", line 18, in chatbot = hugchat.ChatBot(cookies=cookies.get_dict()) File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 49, in **init** self.current_conversation = self.new_conversation() File "C:\Users\D4RK_D4NTE\PycharmProjects\pythonProject2\venv\lib\site-packages\hugchat\hugchat.py", line 132, in new_conversation raise CreateConversationError(f"Failed to create new conversation. ({err_count})") hugchat.exceptions.CreateConversationError: Failed to create new conversation. (6)
> 
> Process finished with exit code 1

The `logging.DEBUG` adds additional logging to the stdout, not to the error message. If you could send your whole console output and not just the error message that would be great.
