### ISSUE TITLE
Error tha comes

### ISSUE THREAD

**Issue by wambugu71** [Soulter/hugging-chat-api#114]
Any one experiencing the error ?
``` Python
Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 570, in _stream_query

    _type = obj["type"]

KeyError: 'type'

2023-10-15 10:46:45.616 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 570, in _stream_query

    _type = obj["type"]

KeyError: 'type'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 77, in __next__

    a: dict = next(self.g)

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 601, in _stream_query

    raise ChatError(f"Failed to parse response: {res}")

hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/meta-llama2-70b-chat/mainhug.py", line 71, in <module>

    assistant_response = chatwithme().query(prompt,temperature= 0.5, max_new_tokens= 4029)['text']#chatbot.chat(prompt)['text']

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 204, in __getitem__

    self.wait_until_done()

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 166, in wait_until_done

    self.__next__()

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 120, in __next__

    raise StopIteration

StopIteration
```
Any way to handle the error?

**Comment by Whitelisted1** [comment]
That certainly is odd. While I was testing I had this error once but I was unable to reproduce it after that. If you are still having this error, could you try adding the following lines to your code so we can get the debug output?
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by wambugu71** [comment]
I think the error is on the server sided it's status 500. Check the logs
``` Python
DEBUG:watchdog.observers.inotify_buffer:in-event <InotifyEvent: src_path=b'/mount/src/meta-llama2-70b-chat/metallma2wambugu/__pycache__', wd=2, mask=IN_ISDIR|IN_OPEN, cookie=0, name=''>

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443

DEBUG:urllib3.connectionpool:https://huggingface.co:443 "POST /chat/conversation/652c168cddbc34c599ddfc65 HTTP/1.1" 200 None

DEBUG:urllib3.connectionpool:Resetting dropped connection: huggingface.co

DEBUG:urllib3.connectionpool:https://huggingface.co:443 "GET /chat/conversation/652c168cddbc34c599ddfc65/__data.json?x-sveltekit-invalidated=1_ HTTP/1.1" 200 None

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443

DEBUG:urllib3.connectionpool:https://huggingface.co:443 "POST /chat/conversation/652c168cddbc34c599ddfc65 HTTP/1.1" 500 28

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 570, in _stream_query

    _type = obj["type"]

KeyError: 'type'

2023-10-15 16:45:29.857 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 570, in _stream_query

    _type = obj["type"]

KeyError: 'type'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 77, in __next__

    a: dict = next(self.g)

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 601, in _stream_query

    raise ChatError(f"Failed to parse response: {res}")

hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/meta-llama2-70b-chat/mainhug.py", line 71, in <module>

    assistant_response = chatwithme().query(prompt,temperature= 0.5, max_new_tokens= 4029)['text']

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 204, in __getitem__

    self.wait_until_done()

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 166, in wait_until_done

    self.__next__()

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/message.py", line 120, in __next__

    raise StopIteration

StopIteration
```
It frequently happens though.

**Comment by batlahiya** [comment]
I am  experiencing the same issue

**Comment by ogios** [comment]
@wambugu71 yes, it says `Internal Error` which means somthing went wrong on the server side
what we can do is just capture this error and raise it directly

**Comment by ogios** [comment]
does it happens randomly? what model you are using? does other models have this problem frequently like this?
i dont know if it's too many request or something wrong about the request body that makes the server raise unhandled error.

**Comment by Whitelisted1** [comment]
> does it happens randomly? what model you are using? does other models have this problem frequently like this? i dont know if it's too many request or something wrong about the request body that makes the server raise unhandled error.

Earlier when I was testing I was getting the error more commonly, about one in every 10 or so messages, but I am not getting the error now. While I was testing I also ran into a different rate limiting error message, so we know that that is not the problem. I am currently using the default model, `meta-llama/Llama-2-70b-chat-hf`

**Comment by wambugu71** [comment]
> does it happens randomly? what model you are using? does other models have this problem frequently like this? i dont know if it's too many request or something wrong about the request body that makes the server raise unhandled error.

Yes I the model is `meta-llama2-70b` in where the ```Python 
chatbot.switch_llm(3)
``` does not work, the model remains to be `meta-llama2-70b` even if you change it.

**Comment by ogios** [comment]
> Yes I the model is `meta-llama2-70b` in where the 
> ``` Python 
> chatbot.switch_llm(3)
> ``` 
> does not work, the model remains to be `meta-llama2-70b` even if you change it. 

are you trying to change model of an existing conversation? if you do then it's not allowed.

**Comment by wambugu71** [comment]
> > Yes I the model is `meta-llama2-70b` in where the
> > ```
> > chatbot.switch_llm(3)
> > ```
> > 
> > 
> > does not work, the model remains to be `meta-llama2-70b` even if you change it.
> 
> are you trying to change model of an existing conversation? if you do then it's not allowed.


> > Yes I the model is `meta-llama2-70b` in where the
> > ```
> > chatbot.switch_llm(3)
> > ```
> > 
> > 
> > does not work, the model remains to be `meta-llama2-70b` even if you change it.
> 
> are you trying to change model of an existing conversation? if you do then it's not allowed.

How do I switch between the models. 
Would you mind if you send me. Example code on Switching to a new model?, because I have been using 
``` Python 
chatbot.switch_llm(<the index after getting the available models>)
``` 
In which it doesn't work, to change the indexed model.

**Comment by wambugu71** [comment]
> > How do I switch between the models. Would you mind if you send me. Example code on Switching to a new model?, because I have been using
> > ```
> > chatbot.switch_llm(<the index after getting the available models>)
> > ```
> > 
> > 
> > In which it doesn't work, to change the indexed model.
> 
> one conversation can only be created with one given model and can not be changed afterward. `switch_llm()` is for next time create a conversation with the switched model. a recent PR add a param `modelIndex` in function `new_conversation()`: [#115](https://github.com/Soulter/hugging-chat-api/pull/115/files#diff-1d4fe39f4b8bf40e9176a3af9724419bac7eae3bad6401284c62520737b5d904R204). and now you can just:
> 
> ```python
> chatbot.new_conversation(modelIndex=<the index after getting the available models>)
> ```

Error occurs trying to create a new conversation as directed above.
Error output
``` Python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hugchat/hugchat.py", line 234, in new_conversation
    cid = json.loads(resp.text)['conversationId']
KeyError: 'conversationId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):                      File "/root/chatbot.py", line 44, in <module>
    chatbot.new_conversation(3)
  File "/usr/local/lib/python3.10/dist-packages/hugchat/hugchat.py", line 253, in new_conversation
    raise CreateConversationError(                    hugchat.exceptions.CreateConversationError: Failed to create new conversation with status code: 500. (6)
```

**Comment by wambugu71** [comment]
I did it the wrong way.Now I have got it right...
It should be
``` Python
chatbot.switch_llm(<index>)
chatbot.new_conversation(switch_to =True)
```

**Comment by wambugu71** [comment]
I think my issues are resolved thanks in advance
