### ISSUE TITLE
No connection to hugchat

### ISSUE THREAD

**Issue by DeuDeuka** [Soulter/hugging-chat-api#12]
I tried to connect to chatbot and saw this
`[Error] Failed to create new conversation. Retrying... (1)
[Error] Failed to create new conversation. Retrying... (2)
[Error] Failed to create new conversation. Retrying... (3)
[Error] Failed to create new conversation. Retrying... (4)
[Error] Failed to create new conversation. Retrying... (5)
[Error] Failed to create new conversation. Retrying... (6)
Traceback (most recent call last):
  File "C:/Users/DeuDeuka/Videos/newgpt.py", line 12, in <module>
    chatbot = hugchat.ChatBot()
  File "C:\Users\DeuDeuka\AppData\Roaming\Python\Python310\site-packages\hugchat\hugchat.py", line 12, in __init__
    self.current_conversation = self.new_conversation()
  File "C:\Users\DeuDeuka\AppData\Roaming\Python\Python310\site-packages\hugchat\hugchat.py", line 49, in new_conversation
    raise e
  File "C:\Users\DeuDeuka\AppData\Roaming\Python\Python310\site-packages\hugchat\hugchat.py", line 42, in new_conversation
    cid = json.loads(resp.text)['conversationId']
KeyError: 'conversationId'`

**Comment by RockChinQ** [comment]
It can be a problem of protocol, `GET  "https://huggingface.co/chat/conversation" returns:

```
{"message":"Internal Error"}
```

**Comment by DeuDeuka** [comment]
nope
![image](https://user-images.githubusercontent.com/89848752/236231125-0db91565-68d6-456a-87e3-e19e1ae643b5.png)

**Comment by Soulter** [comment]
> nope ![image](https://user-images.githubusercontent.com/89848752/236231125-0db91565-68d6-456a-87e3-e19e1ae643b5.png)

It seems like you are not import the `hugchat` package directly.
You should use it like this way:
```
from hugchat import hugchat
chatbot = hugchat.ChatBot()
print(chatbot.chat("hello"))
```

**Comment by indrani92** [comment]
Hi 
I am still facing the same problem even after upgrade.  When I call  GET  "https://huggingface.co/chat/conversation" in cmd line it gives cannot resolve proxy. But in browser the url works.

**Comment by Soulter** [comment]
> 

HuggingChat just updated their protocol. Thank you for your reminder! I will fix it soon.

**Comment by Soulter** [comment]
> Hi I am still facing the same problem even after upgrade. When I call GET "https://huggingface.co/chat/conversation" in cmd line it gives cannot resolve proxy. But in browser the url works.

HuggingChat just updated their protocol. Thank you for your reminder! I will fix it soon.

**Comment by Soulter** [comment]
> Hi I am still facing the same problem even after upgrade. When I call GET "https://huggingface.co/chat/conversation" in cmd line it gives cannot resolve proxy. But in browser the url works.

Fixed. Try to use the latest version 0.0.5.4

**Comment by Lorg0n** [comment]
`hugchat            0.0.5.4`

Not working:
```[Error] Failed to create new conversation. Retrying... (1)
[Error] Failed to create new conversation. Retrying... (2)
[Error] Failed to create new conversation. Retrying... (3)
[Error] Failed to create new conversation. Retrying... (4)
[Error] Failed to create new conversation. Retrying... (5)
Traceback (most recent call last):
  File "C:\Users\*\PycharmProjects\nicechat\main.py", line 9, in <module>
    chatbot = hugchat.ChatBot()
  File "C:\Users\*\PycharmProjects\nicechat\venv\lib\site-packages\hugchat\hugchat.py", line 12, in __init__
    self.now_conversation = self.new_conversation()
  File "C:\Users\*\PycharmProjects\nicechat\venv\lib\site-packages\hugchat\hugchat.py", line 39, in new_conversation
    raise e
  File "C:\Users\*\PycharmProjects\nicechat\venv\lib\site-packages\hugchat\hugchat.py", line 34, in new_conversation
    return json.loads(resp.text)['conversationId']
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\*\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[Error] Failed to create new conversation. Retrying... (6)

**Comment by divinenaman** [comment]
I was trying to debug #37 but getting this error when I try to use the repo locally (with or without changes) while a google-collab with latest packge works with same cookies: 
```python

Traceback (most recent call last):
  File "/home/naman/baasha/hugging-chat-api/venv/lib/python3.10/site-packages/hugchat/hugchat.py", line 189, in new_conversation
    cid = json.loads(resp.text)['conversationId']
KeyError: 'conversationId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/naman/baasha/hugging-chat-api/main.py", line 9, in <module>
    bot = hugchat.ChatBot(cookies=hugging_chat_cookies)
  File "/home/naman/baasha/hugging-chat-api/venv/lib/python3.10/site-packages/hugchat/hugchat.py", line 100, in __init__
    self.current_conversation = self.new_conversation()
  File "/home/naman/baasha/hugging-chat-api/venv/lib/python3.10/site-packages/hugchat/hugchat.py", line 199, in new_conversation
    raise CreateConversationError(f"Failed to create new conversation. ({err_count})")
hugchat.exceptions.CreateConversationError: Failed to create new conversation. (6)

````
Steps I did:
- git clone
- pip install .
- python -m hugchat.hugchat

**Comment by jackrite** [comment]
same error it works in google colab but not in local machine
