### ISSUE TITLE
Error Requests

### ISSUE THREAD

**Issue by AravindRohit** [Soulter/hugging-chat-api#170]
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\Local_ApI\2.py", line 10, in <module>
    cookies = sign.login()
              ^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\Local_ApI\venv\Lib\site-packages\hugchat\login.py", line 126, in login
    location = self.getAuthURL()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\Local_ApI\venv\Lib\site-packages\hugchat\login.py", line 94, in getAuthURL
    raise Exception("Something went wrong!")
Exception: Something went wrong!

**Comment by AravindRohit** [comment]
It gets this error yesterday it is working only

**Comment by Soulter** [comment]
#169

**Comment by Soulter** [comment]
The problem has been solved.
