### ISSUE TITLE
Not Working Currently

### ISSUE THREAD

**Issue by littlecubcub** [Soulter/hugging-chat-api#182]
Response
    raise ChatError(f"Server returns an error: {obj['message']}")
hugchat.exceptions.ChatError: Server returns an error: Internal Error
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\hugchat\hugchat.py", line 704, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x0000029D19AC9700>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\hugchat\hugchat.py", line 730, in _stream_query
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}

**Comment by Soulter** [comment]
https://github.com/Soulter/hugging-chat-api/issues/171

Please update hugchat.

**Comment by YoussefBechara** [comment]
Hello Soulter i already upfated hugchat and it didnt work

**Comment by YoussefBechara** [comment]
I fixed it by unionstalling hugchat in my env , then installing it via : py -m pip install hugchat
