### ISSUE TITLE
When i try to print or str the query or if i touch it , it gives me this error:

### ISSUE THREAD

**Issue by YoussefBechara** [Soulter/hugging-chat-api#183]
ERROR:root:No `type` found in response: {'message': 'Internal Error'}
Traceback (most recent call last):
  File "c:\Users\user\Desktop\TikTokAiFactsAutomater\hug_chat_api.py", line 28, in <module>
    response = ask_hugchat(txt)
               ^^^^^^^^^^^^^^^^
  File "c:\Users\user\Desktop\TikTokAiFactsAutomater\hug_chat_api.py", line 11, in ask_hugchat
    query_result = str(chatbot.query(text))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\message.py", line 228, in __str__   
    return self.wait_until_done()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\message.py", line 194, in wait_until_done
    self.__next__()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\message.py", line 149, in __next__  
    raise self.error
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\message.py", line 100, in __next__  
    self._filterResponse(a)
onse
    raise ChatError(f"Server returns an error: {obj['message']}")
hugchat.exceptions.ChatError: Server returns an error: Internal Error
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\hugchat.py", line 700, in _stream_query
    yield obj
GeneratorExit
Exception ignored in: <generator object ChatBot._stream_query at 0x00000259D031B4C0>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\hugchat.py", line 726, in _stream_query
hugchat.exceptions.ChatError: Failed to parse response: {"message":"Internal Error"}

**Comment by YoussefBechara** [comment]
I fixed it by unionstalling hugchat in my env , then installing it via : py -m pip install hugchat

**Comment by Soulter** [comment]
duplicate with https://github.com/Soulter/hugging-chat-api/issues/171

**Comment by Soulter** [comment]
> I fixed it by unionstalling hugchat in my env , then installing it via : py -m pip install hugchat

the latest version has fixed the bug ;)
