### ISSUE TITLE
In login 

### ISSUE THREAD

**Issue by FERRAMOS888** [Soulter/hugging-chat-api#186]
**Describe the bug**
When login to account .

Traceback (most recent call last):
  File "C:\Users\Migue\Desktop\BioBert-sp\chatgptopen.py", line 57, in <module>
    cookies = sign.login()
              ^^^^^^^^^^^^
  File "C:\Users\Migue\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 34, in login
    location = self._get_auth_url()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Migue\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 158, in _get_auth_url
    raise Exception("Something went wrong!")
Exception: Something went wrong!

**Comment by christianderrico** [comment]
"https://huggingface.co/chat/login" URL doesn't answer and says "Bad Gateway Error"

**Comment by FERRAMOS888** [comment]
Is right now
