### ISSUE TITLE
Hugging Face API raising error "Uncaught app exception" & "raise Exception("Something went wrong!")"

### ISSUE THREAD

**Issue by Areebkhan02** [Soulter/hugging-chat-api#206]
**Describe the bug**
So I made a chatbot using a public repository and multiple online resources through Hugchat API and used the model "CohereForAI/c4ai-command-r-plus". I then proceeded to host it on streamlit. All was working fine and the prompts that I was giving it worked perfectly. I then commited my code and proceed to do another work. After 6 to 7 hours when I tried the bot it was saying "Exception: Something went wrong!". I looked into my vs code there as error which very precisely resembles the error identified in this post: [https://github.com/Soulter/hugging-chat-api/issues/169](url)

**To Reproduce**
To reproduce this error I am attaching my code here `# Imports
import os
from hugchat import hugchat
from hugchat.login import Login
from dotenv import load_dotenv

# Load the environment variables
#load_dotenv()

# Load the email and password from the environment variables
EMAIL = ''
PASSWD = ''

# Sign in to the HugChat
user = Login(email=EMAIL, passwd=PASSWD)

# Function to prepare the query
def prepare_query(user_inputs):
    # Initialize the query
    query = ""

    # Add project-specific information
    

    # Loop through the user inputs
    for key, value in user_inputs.items():
        # Add the key and value to the query
        query += f"{key}: {value}\n"

    # Add a new line at the end of the query
    query += "Give me a solution for this issue or give me some information about it."

    # Return the query
    return query

# Function to get the chatbot
def get_chatbot():

    # Set the cookies path
    COOKIES_PATH = "cookies.json"

    # Save the cookies
    cookies = user.login(cookie_dir_path=COOKIES_PATH)

    # Initialize the chatbot
    chatbot = hugchat.ChatBot(
        cookies=cookies.get_dict(), default_llm="CohereForAI/c4ai-command-r-plus"
    )

    # Return the chatbot
    return chatbot

# Function to get the response from the chatbot
def get_response(user_inputs):
    # Get the chatbot
    chatbot = get_chatbot()

    # Prepare the query
    query = prepare_query(user_inputs)

    # Get the response from the chatbot
    response = chatbot.chat(query)

    # Return the response
    return response
`
you can enter your own email and password. The error I am receiving is 

> `2024-05-03 18:28:08.164 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\pages\01_🤖_Simple_ChatBot.py", line 69, in <module>
    response = get_response(user_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 63, in get_response
    chatbot = get_chatbot()
              ^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 49, in get_chatbot
    cookies = user.login(cookie_dir_path=COOKIES_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 47, in login
    location = self._get_auth_url()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 175, in _get_auth_url
    raise Exception("Something went wrong!")
Exception: Something went wrong!
2024-05-03 18:32:31.068 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\pages\01_🤖_Simple_ChatBot.py", line 69, in <module>
    response = get_response(user_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 63, in get_response
    chatbot = get_chatbot()
              ^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 49, in get_chatbot
    cookies = user.login(cookie_dir_path=COOKIES_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 47, in login
    location = self._get_auth_url()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 175, in _get_auth_url
    raise Exception("Something went wrong!")
Exception: Something went wrong!
2024-05-03 18:32:41.286 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\pages\01_🤖_Simple_ChatBot.py", line 69, in <module>
    response = get_response(user_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 63, in get_response
    chatbot = get_chatbot()
              ^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 49, in get_chatbot
    cookies = user.login(cookie_dir_path=COOKIES_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 47, in login
    location = self._get_auth_url()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 175, in _get_auth_url
    raise Exception("Something went wrong!")
Exception: Something went wrong!
2024-05-03 18:36:21.048 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\pages\01_🤖_Simple_ChatBot.py", line 69, in <module>
    response = get_response(user_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 63, in get_response
    chatbot = get_chatbot()
              ^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 49, in get_chatbot
    cookies = user.login(cookie_dir_path=COOKIES_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 47, in login
    location = self._get_auth_url()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 175, in _get_auth_url
    raise Exception("Something went wrong!")
Exception: Something went wrong!
2024-05-03 18:41:57.633 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\pages\01_🤖_Simple_ChatBot.py", line 69, in <module>
    response = get_response(user_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 63, in get_response
    chatbot = get_chatbot()
              ^^^^^^^^^^^^^
  File "C:\Users\DELL\Documents\GitHub\IntelliCropPK_ChatBot\helper.py", line 49, in get_chatbot
    cookies = user.login(cookie_dir_path=COOKIES_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 47, in login
    location = self._get_auth_url()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\hugchat\login.py", line 175, in _get_auth_url
    raise Exception("Something went wrong!")
Exception: Something went wrong!`

Same error which was identified in the post.
**Expected behavior**

**Screenshots**
![image](https://github.com/Soulter/hugging-chat-api/assets/84643515/1a8a1c76-652b-4b50-a9ed-7550c63c023b)

**Comment by Areebkhan02** [comment]
what I have already done is 
1) I have deleted the hugchat library and installed the lastest version
2) have disconnected my hugging face account with hug chat and connected again

but nothing seems to work but it was working fine previously

**Comment by vuemquan** [comment]
same

PS D:\chat> python new.py
Traceback (most recent call last):
  File "D:\chat\new.py", line 9, in <module>
    cookies = sign.login(cookie_dir_path=cookie_path_dir, save_cookies=True)
  File "C:\Program Files\Python310\lib\site-packages\hugchat\login.py", line 47, in login
    location = self._get_auth_url()
  File "C:\Program Files\Python310\lib\site-packages\hugchat\login.py", line 175, in _get_auth_url
    raise Exception("Something went wrong!")
Exception: Something went wrong!

**Comment by Areebkhan02** [comment]
are you using this tutorial -> "https://dev.to/codemaker2015/build-llm-powered-chatbot-in-5-minutes-using-hugchat-and-streamlit-2f53" ?

**Comment by kokofixcomputers** [comment]
please fix this!!!! same!

**Comment by kokofixcomputers** [comment]
hey guys! i found a solution!

**Comment by kokofixcomputers** [comment]
waiting for my pull request to get merged

**Comment by Areebkhan02** [comment]
Please tell us the solution if there is any.

**Comment by Soulter** [comment]
Hey guys, I just released a version `v0.4.4` that fixed the bug by @kokofixcomputers , you can update hugchat to check it again. Thanks @kokofixcomputers

**Comment by kokofixcomputers** [comment]
> Hey guys, I just released a version `v0.4.4` that fixed the bug by @kokofixcomputers , you can update hugchat to check it again. Thanks @kokofixcomputers

thank you so much for responding quickly! i have my issue fixed!

**Comment by Areebkhan02** [comment]
Thankyou @Soulter and @kokofixcomputers  !!

**Comment by kokofixcomputers** [comment]
No problem
