### ISSUE TITLE
Failed to accept ethics modal with status code

### ISSUE THREAD

**Issue by alextomdog** [Soulter/hugging-chat-api#21]
- python version 
Python 3.9.13, windows11 

- response error 
when i run the cmd `pip install hugchat`and run the example code:
```
(venv) PS C:\Users\zhaom\Desktop\code\pycode> & c:/Users/zhaom/Desktop/code/pycode/venv/Scripts/python.exe c:/Users/zhaom/Desktop/code/pycode/test.py   
Traceback (most recent call last):
  File "c:\Users\zhaom\Desktop\code\pycode\test.py", line 3, in <module>
    chatbot = hugchat.ChatBot()
  File "C:\Users\zhaom\Desktop\code\pycode\venv\lib\site-packages\hugchat\hugchat.py", line 13, in __init__
    self.current_conversation = self.new_conversation()
  File "C:\Users\zhaom\Desktop\code\pycode\venv\lib\site-packages\hugchat\hugchat.py", line 73, in new_conversation
    self.accept_ethics_modal()
  File "C:\Users\zhaom\Desktop\code\pycode\venv\lib\site-packages\hugchat\hugchat.py", line 64, in accept_ethics_modal
    raise Exception(f"Failed to accept ethics modal with status code {response.status_code}. {response.content.decode()}")
Exception: Failed to accept ethics modal with status code 401. You have to be logged in.
```

**Comment by Soulter** [comment]
#20

**Comment by RockChinQ** [comment]
#20 fixed

**Comment by Soulter** [comment]
Update hugchat to the latest version `0.0.6`
```bash
pip install hugchat --upgrade
```
