### ISSUE TITLE
Chatbot not found error

### ISSUE THREAD

**Issue by Aravind4525** [Soulter/hugging-chat-api#251]
I am using hugchat 0.4.9 version it gets error 

Traceback (most recent call last):
  File "C:\Users\ARAVIND\PycharmProjects\CourseSearch\bc_pi.py", line 160, in <module>
    result = pisearch_courses(searchinput=input_text, course_content_id=course_content_id, standard=level,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ARAVIND\PycharmProjects\CourseSearch\bc_ut.py", line 634, in inner
    f = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ARAVIND\PycharmProjects\CourseSearch\bc_pi.py", line 16, in pisearch_courses
    chat_response = perform_query(searchinput)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ARAVIND\PycharmProjects\CourseSearch\bc_ut.py", line 1627, in perform_query
    query_result = chatbot.query(
                   ^^^^^^^
NameError: name 'chatbot' is not defined

I have upgraded this to latest 0.4.10 but it gets same error

**Comment by Soulter** [comment]
Maybe you haven't initialize `chatbot`.
