### ISSUE TITLE
 Failed to parse response:

### ISSUE THREAD

**Issue by JayDesignDevelope** [Soulter/hugging-chat-api#257]
**Describe the bug**
unable to get respone , previously 2 weeks back everything worked fine, but all of a sudden facing  Failed to parse response:: {"message":"An error occurred","errorId":"8f9975a9-2ad5-4688-9284-bc085d65c4bf"}

**To Reproduce**
, line 108, in _filterResponse
    raise ChatError(f"Server returns an error: {obj['message']}")
hugchat.exceptions.ChatError: Server returns an error: An error occurred
 after hitting the get response froma. streamlit app , having this indeside /hugchat/message.py"
**Expected behavior**
response should be normal previously but now having this issue
**Screenshots**
![image](https://github.com/user-attachments/assets/ca46f137-fa7e-463d-ad78-a9a983ef7f1c)

**Additional context**
What Operating System are you using?- mac os, m2 chip
What Python version are you using? python 3.9
What version of hugchat are you using? 0.4.11

**Comment by Aravind4525** [comment]
ERROR:root:No `type` found in response: {'message': 'An error occurred', 'errorId': '5c3eb302-2cc4-40b4-9c1f-e8487211fa77'}
Traceback (most recent call last):
  File "D:\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_repr_utils.py", line 213, in get_value_repr
    value_representation = format % value
                           ~~~~~~~^~~~~~~
  File "C:\Users\Admin\PycharmProjects\Document Intelligence\venv\Lib\site-packages\hugchat\message.py", line 292, in __str__
    return self.wait_until_done()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\Document Intelligence\venv\Lib\site-packages\hugchat\message.py", line 265, in wait_until_done
    raise self.error
  File "D:\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_repr_utils.py", line 209, in get_value_repr
    value_representation = pydevd_repr_function(value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\reprlib.py", line 53, in repr
    return self.repr1(x, self.maxlevel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\reprlib.py", line 63, in repr1
    return self.repr_instance(x, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PyCharm Community Edition 2023.2\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_repr_utils.py", line 171, in repr_instance
    return str(x)
           ^^^^^^
  File "C:\Users\Admin\PycharmProjects\Document Intelligence\venv\Lib\site-packages\hugchat\message.py", line 292, in __str__
    return self.wait_until_done()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\Document Intelligence\venv\Lib\site-packages\hugchat\message.py", line 259, in wait_until_done
    self.__next__()
  File "C:\Users\Admin\PycharmProjects\Document Intelligence\venv\Lib\site-packages\hugchat\message.py", line 200, in __next__
    raise self.error
  File "C:\Users\Admin\PycharmProjects\Document Intelligence\venv\Lib\site-packages\hugchat\message.py", line 124, in __next__
    self._filterResponse(data)
  File "C:\Users\Admin\PycharmProjects\Document Intelligence\venv\Lib\site-packages\hugchat\message.py", line 108, in _filterResponse
    raise ChatError(f"Server returns an error: {obj['message']}")
hugchat.exceptions.ChatError: Server returns an error: An error occurred

**Comment by Aravind4525** [comment]
I am using hugchat 0.4.9 
and if i use latest version it is getting text as invalid parameter
