### ISSUE TITLE
The bug with parse

### ISSUE THREAD

**Issue by dscss1** [Soulter/hugging-chat-api#266]
**Describe the bug**
IDK

**To Reproduce**
```
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 14570)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/container/bot.py", line 17, in <module>
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/hugchat/hugchat.py", line 74, in __init__
    self.llms = self.get_remote_llms()
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/hugchat/hugchat.py", line 414, in get_remote_llms
    data = r.json()["nodes"][0]["data"]
           ^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 2 column 1 (char 14570)
```

**Expected behavior**
I running my script with using the hugchatapi  and this not working

**Additional context**
Ubuntu 22.04 LTS Docker
Python 3.11
The latest

**Comment by we09532** [comment]
I got the same issue too `[27088] Failed to execute script 'main' due to unhandled exception!

json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 11832)

The above error occurred on 
The above error occurred on `

**Comment by Aravind4525** [comment]
chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

**Comment by Aravind4525** [comment]
when it will be fixed?

**Comment by dscss1** [comment]
Update the library

**Comment by dscss1** [comment]
Hello @perbeesh 
I fixed the bug 
Updated a library
