### ISSUE TITLE
Json error 

### ISSUE THREAD

**Issue by wambugu71** [Soulter/hugging-chat-api#78]
``` Python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/hugchat/hugchat.py", line 397, in chat
    obj = json.loads(res[5:])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/chatbot.py", line 26, in <module>
    for letter in chatbot.chat(prompt):
  File "/usr/local/lib/python3.10/dist-packages/hugchat/hugchat.py", line 401, in chat
    raise ChatError(f"Failed to parse response: {res}")
hugchat.exceptions.ChatError: Failed to parse response: {"type":"status","status":"started"}
```

**Comment by mryellowdog** [comment]
I'm getting this same error as well

**Comment by jackfood** [comment]
I believe it just happened yesterday out of sudden.

**Comment by Soulter** [comment]
Hey guys I have detected the problem and I will fix the bug.

**Comment by Soulter** [comment]
v0.2.6 fixed
