### ISSUE TITLE
Failing to create a new conversation! 

### ISSUE THREAD

**Issue by sangshah** [Soulter/hugging-chat-api#90]
File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "/mount/src/chatty-pants/streamlit_app.py", line 64, in <module>
    response = generate_response(prompt, hf_email, hf_pass)
File "/mount/src/chatty-pants/streamlit_app.py", line 45, in generate_response
    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())
File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 49, in __init__
    self.current_conversation = self.new_conversation()
File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 132, in new_conversation
    raise CreateConversationError(f"Failed to create new conversation. ({err_count})")

**Comment by Whitelisted1** [comment]
Make sure that you have updated your version of hugchat
You can do this by executing the command `pip install hugchat --upgrade`

**Comment by sangshah** [comment]
I have a streamlit app and have specified the latest version of the hugging-chat-api. 

https://github.com/sangshah/chatty-pants



`2023-09-30 23:03:44.498 Uncaught app exception

Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 124, in new_conversation

    cid = json.loads(resp.text)['conversationId']

KeyError: 'conversationId'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script

    exec(code, module.__dict__)

  File "/mount/src/chatty-pants/streamlit_app.py", line 64, in <module>

    response = generate_response(prompt, hf_email, hf_pass)

  File "/mount/src/chatty-pants/streamlit_app.py", line 45, in generate_response

    chatbot = hugchat.ChatBot(cookies=cookies.get_dict())

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 49, in __init__

    self.current_conversation = self.new_conversation()

  File "/home/adminuser/venv/lib/python3.9/site-packages/hugchat/hugchat.py", line 132, in new_conversation

    raise CreateConversationError(f"Failed to create new conversation. ({err_count})")

hugchat.exceptions.CreateConversationError: Failed to create new conversation. (6)`

**Comment by sangshah** [comment]
Got it working.
